# Generated by Django 2.2.3 on 2019-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Hotel Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('n_tables', models.IntegerField(verbose_name='Number of tables')),
                ('c_no', models.CharField(max_length=10, unique=True, verbose_name='Contact No')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_hotel', models.IntegerField(default=0, verbose_name='Hotel ID')),
                ('reservation_name', models.CharField(max_length=30, verbose_name='register user')),
                ('reservation_date', models.CharField(max_length=30, verbose_name='enter time and date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
            ],
        ),
    ]
