# Generated by Django 2.2.3 on 2019-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact',
            field=models.TextField(blank=True, max_length=10, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(max_length=30, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_name',
            field=models.CharField(max_length=30, verbose_name='Reservation Name'),
        ),
    ]
