# Generated by Django 2.2.3 on 2019-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='n_tables',
            field=models.IntegerField(verbose_name='Number of tables Available'),
        ),
    ]
