# Generated by Django 2.2.3 on 2019-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190711_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact',
            field=models.TextField(max_length=10, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default=0, max_length=10, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Password'),
        ),
    ]
