# Generated by Django 2.2.3 on 2019-07-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190711_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_people',
            field=models.IntegerField(null=True, verbose_name='Number of People'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
